version: "3.9"

# 2 more docker services for FE and BE could be added, so that all 3 services are started via one command.
services:
  postgres:
    image: postgres
    env_file:
      - ./server/.env
    ports:
      - "5432:5432"
    volumes:
      - pg-data:/var/lib/postgresql
volumes:
  pg-data:
